draw_set_color(c_black)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
draw_set_font(F_02)
draw_text(x,y,"A Continuacion, se te presentaran cada una de las imagenes que obedecen a cada una de las 6 categorias.")